use ecommerce;


## BASIC PROBLEMS:

# 1.List all unique cities where customers are located
SELECT DISTINCT customer_city
FROM customers;


# 2. Count the number of orders placed in 2017

SELECT COUNT(*) AS total_orders_2017
FROM orders
WHERE YEAR(order_purchase_timestamp) = 2017;


# 3. Find the total sales per category. 

SELECT 
    p.product_category,
    ROUND(SUM(oi.price), 2) AS total_sales
FROM order_item oi
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY p.product_category
ORDER BY total_sales DESC;

# 4. Calculate the percentage of orders that were paid in installments.

SELECT 
    (SUM(CASE WHEN payment_installments > 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) 
    AS installment_percentage
FROM payments;

# 5. Count the number of customers from each state

SELECT 
    customer_state, 
    COUNT(*) AS customer_count
FROM customers
GROUP BY customer_state
ORDER BY customer_count DESC;


## INTERMEDIATE PROBLEMS: 

# 1. Calculate the number of orders per month in 2018.

SELECT 
    MONTH(order_purchase_timestamp) AS month,
    COUNT(*) AS order_count
FROM orders
WHERE YEAR(order_purchase_timestamp) = 2018
GROUP BY MONTH(order_purchase_timestamp)
ORDER BY month;

# 2.  Find the average number of products per order, grouped by customer city. 

SELECT 
    c.customer_city,
    AVG(order_product_count) AS avg_products_per_order
FROM (
    SELECT 
        o.order_id,
        o.customer_id,
        COUNT(oi.product_id) AS order_product_count
    FROM orders o
    JOIN order_item oi ON o.order_id = oi.order_id
    GROUP BY o.order_id, o.customer_id
) AS order_counts
JOIN customers c ON order_counts.customer_id = c.customer_id
GROUP BY c.customer_city
ORDER BY avg_products_per_order DESC;

# 3. Calculate the percentage of total revenue contributed by each product category. 

SELECT 
    p.product_category AS category,
    Round(SUM(oi.price) * 100.0 / (SELECT SUM(price) FROM order_item),2) AS revenue_percentage
FROM order_item oi
JOIN products p 
    ON oi.product_id = p.product_id
GROUP BY p.product_category
ORDER BY revenue_percentage DESC;

# 4. Identify the correlation between product price and the number of times a product has been purchased.

SELECT 
    (AVG(avg_price * purchase_count) - AVG(avg_price) * AVG(purchase_count)) /
    (STDDEV(avg_price) * STDDEV(purchase_count)) AS price_purchase_correlation
FROM (
    SELECT 
        product_id,
        AVG(price) AS avg_price,
        COUNT(order_item_id) AS purchase_count
    FROM order_item
    GROUP BY product_id
) t;

# 5. Calculate the total revenue generated by each seller, and rank them by revenue.

SELECT 
    oi.seller_id,
    SUM(oi.price + oi.freight_value) AS total_revenue
FROM order_item oi
GROUP BY oi.seller_id
ORDER BY total_revenue DESC;

## ADVANCED PROBLEMS: 

# 1. Calculate the moving average of order values for each customer over their order history. 

WITH order_values AS (
    SELECT 
        o.order_id,
        o.customer_id,
        SUM(oi.price + oi.freight_value) AS order_value,
        o.order_purchase_timestamp
    FROM orders o
    JOIN order_item oi 
      ON o.order_id = oi.order_id
    GROUP BY o.order_id, o.customer_id, o.order_purchase_timestamp
)
SELECT 
    customer_id,
    order_id,
    order_purchase_timestamp,
    order_value,
    AVG(order_value) OVER (
        PARTITION BY customer_id
        ORDER BY order_purchase_timestamp
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS moving_avg_order_value
FROM order_values
ORDER BY customer_id, order_purchase_timestamp;

# 2. Calculate the cumulative sales per month for each year. 

WITH monthly_sales AS (
    SELECT 
        EXTRACT(YEAR FROM o.order_purchase_timestamp) AS year,
        EXTRACT(MONTH FROM o.order_purchase_timestamp) AS month,
        SUM(oi.price + oi.freight_value) AS monthly_revenue
    FROM orders o
    JOIN order_item oi 
      ON o.order_id = oi.order_id
    GROUP BY EXTRACT(YEAR FROM o.order_purchase_timestamp),
             EXTRACT(MONTH FROM o.order_purchase_timestamp)
)
SELECT 
    year,
    month,
    monthly_revenue,
    SUM(monthly_revenue) OVER (
        PARTITION BY year 
        ORDER BY month
    ) AS cumulative_revenue
FROM monthly_sales
ORDER BY year, month;

# 3. Calculate the year-over-year growth rate of total sales.

WITH yearly_sales AS (
    SELECT 
        EXTRACT(YEAR FROM o.order_purchase_timestamp) AS year,
        SUM(oi.price + oi.freight_value) AS total_sales
    FROM orders o
    JOIN order_item oi 
      ON o.order_id = oi.order_id
    GROUP BY EXTRACT(YEAR FROM o.order_purchase_timestamp)
)
SELECT 
    year,
    total_sales,
    LAG(total_sales) OVER (ORDER BY year) AS prev_year_sales,
    ROUND(
        ( (total_sales - LAG(total_sales) OVER (ORDER BY year)) 
          / LAG(total_sales) OVER (ORDER BY year) ) * 100, 2
    ) AS yoy_growth_rate
FROM yearly_sales
ORDER BY year;

# 4. Calculate the retention rate of customers, defined as the percentage of customers
# who make another purchase within 6 months of their first purchase.

WITH first_purchase AS (
    SELECT 
        customer_id,
        MIN(CAST(order_purchase_timestamp AS DATETIME)) AS first_order_date
    FROM orders
    GROUP BY customer_id
),
retained_customers AS (
    SELECT DISTINCT fp.customer_id
    FROM first_purchase fp
    JOIN orders o 
      ON fp.customer_id = o.customer_id
     AND CAST(o.order_purchase_timestamp AS DATETIME) > fp.first_order_date
     AND CAST(o.order_purchase_timestamp AS DATETIME) <= DATE_ADD(fp.first_order_date, INTERVAL 6 MONTH)
)
SELECT 
    COUNT(rc.customer_id) * 100.0 / COUNT(fp.customer_id) AS retention_rate_percentage
FROM first_purchase fp
LEFT JOIN retained_customers rc 
  ON fp.customer_id = rc.customer_id;

# 5. Identify the top 3 customers who spent the most money in each year.

WITH customer_yearly_spend AS (
    SELECT 
        o.customer_id,
        EXTRACT(YEAR FROM CAST(o.order_purchase_timestamp AS DATETIME)) AS year,
        SUM(oi.price + oi.freight_value) AS total_spent
    FROM orders o
    JOIN order_item oi 
      ON o.order_id = oi.order_id
    GROUP BY o.customer_id, year
),
ranked_customers AS (
    SELECT 
        customer_id,
        year,
        total_spent,
        RANK() OVER (PARTITION BY year ORDER BY total_spent DESC) AS rank_in_year
    FROM customer_yearly_spend
)
SELECT 
    year,
    customer_id,
    total_spent,
    rank_in_year
FROM ranked_customers
WHERE rank_in_year <= 3
ORDER BY year, rank_in_year;
